### ISSUE TITLE
2.1: querySelector & querySelectorAll

### ISSUE THREAD

**Issue by KrijnHoetmer** [SadisticSun/Browser-Technologies#7]
Did you test this demo in IE7? :)

**Comment by TristanJacobs89** [comment]
Doesn't seem to work :(.
My solution would be to see if getElementsByClassName (when classes are used) or getElementsByTagName (when specific tags are needed) would work.

**Comment by KrijnHoetmer** [comment]
Not really the answer I was looking for. Hint: does `forEach` work in IE7?

**Comment by TristanJacobs89** [comment]
No it does not. I did some research and found a plethora of seemingly usable solutions.
The most general one would be:

`if (typeof Array.prototype.forEach != 'function') {
    Array.prototype.forEach = function(callback){
      for (var i = 0; i < this.length; i++){
        callback.apply(this, [this[i], i, this]);
      }
    };
}`

Basically a feature check. Kinda hacky though, manually adding a forEach() loop to the array prototype.

But personally I think the best way would be to just use a basic for loop, since it is supported.
Is this more in line of your thoughts?

**Comment by KrijnHoetmer** [comment]
No, the question was about testing. I assumed you looked at CanIUse, saw IE7 doesn't support `querySelector`, and assumed this demo therefore would say "You're using Internet Explorer 7 or lower.. BOOO!" in that browser. That's why I asked in the first place :) Actually testing your assumption would've pointed you to `forEach`, hence: please _always test_ your assumptions.

It doesn't matter this breaks in IE7, and I know you can fill that gap, but that's not the point I'm trying to make.

**Comment by TristanJacobs89** [comment]
Understood. Thanks!

**Comment by TristanJacobs89** [comment]
Solved: replaced forEach with the basic for-loop.
